---
title: "Project"
author: "PAA"
date: "04 11 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(sjPlot)


```



```{r}
load("C:/Users/Sunshine/Desktop/Biostatistics_2021/Final_project/other_test_results_matched_to_phone_survey_ids.rdata")
load("C:/Users/Sunshine/Desktop/Biostatistics_2021/Final_project/phone_survey_data.rdata")
load("C:/Users/Sunshine/Desktop/Biostatistics_2021/Final_project/test_B_results_matched_to_phone_survey_ids.rdata")
load("C:/Users/Sunshine/Desktop/Biostatistics_2021/Final_project/test_C_results_matched_to_phone_survey_ids.rdata")
load("C:/Users/Sunshine/Desktop/Biostatistics_2021/Final_project/test_D_results_matched_to_phone_survey_ids.rdata")

```


```{r}

data_for_ab_IgG1 <-merge(test_B_results_matched_to_phone_survey_ids, test_C_results_matched_to_phone_survey_ids, by = "ID", all.x = T)

data_for_ab_IgG2 <-merge(data_for_ab_IgG1, test_D_results_matched_to_phone_survey_ids, by = "ID", all.x = T)

str(data_for_ab_IgG2)

data_all<-merge(phone_survey_data, other_test_results_matched_to_phone_survey_ids, by = "ID", all.y = T)

str(data_all)

data_for_ab<- merge(data_for_ab_IgG2, data_all, by = "ID", all.x = T)



data_for_ab<- data_for_ab %>% 
  dplyr::select(c(ID, IgG_testB_quantitative, IgA_or_G_or_M_testC_quantitative, IgG_or_M_testD_quantitative, male, district, age, travelled, used_transport, selftested_covid, selftested_covid_positive, street_used_mask, washing_hands_more, health_level, smoking, smoked_previously, smoking_start_age, smoking_giveup_age, cigarettes_per_day, drinks_coffee, coffee_cups_per_day, times_sick, cough_past, fever_past, sorethroat_past, anosmia_past, runnynose_past, fatigue_past, nosymptoms_past, self_medical_checkups, ct_scan, mri, ultrasonography, fluorography, mammography, x_ray, visit_doctor, no_checkups, allergies, chronical_diseases,wears_glasses, lives_alone, num_people_home, under_18, over_65, spouse_or_partner, other_people, no_pets, dogs, cats, rodents, birds, other_pets, not_sure_pets, income_level, work_status, study_status, received_pension_or_other_support, job_search, manages_people, physical_labour, work_with_people, education_level, cough_now, fever_now, sorethroat_now, anosmia_now, runnynose_now, fatigue_now, nosymptoms_now, IgE_general_quantitative, VitaminD, VitaminD_analyzer, IgG_hpylori, Hemoglobin_A0, Cholesterin, Triglycerides, VLDL, LDL, HDL, Atherogenic_index, neutralizing_antibodies_quantitative))


data_for_ab$Hemoglobin_A0

data_for_ab<- data_for_ab %>% 
mutate(Hem_norm = ifelse (Hemoglobin_A0 < 92, "ниже нормы", ifelse (Hemoglobin_A0 >92 & Hemoglobin_A0 <94, "Норма", "Выше нормы")))


data_for_ab%>%
 mutate(numeric=Hem_norm ) %>% 
  count(Hem_norm, numeric)


data_for_ab$male <- as.factor(data_for_ab$male)

data_for_ab$smoking <- as.factor(data_for_ab$smoking)

head(data_for_ab)


 
```

```{r}

data_ab_only<- data_for_ab %>% 
  dplyr::select(c(ID, IgG_testB_quantitative,IgA_or_G_or_M_testC_quantitative, IgG_or_M_testD_quantitative, neutralizing_antibodies_quantitative))

data_Abbott<-data_for_ab %>% 
  dplyr::select(c(ID, IgG_testB_quantitative, neutralizing_antibodies_quantitative)) %>% filter(IgG_testB_quantitative>=1&neutralizing_antibodies_quantitative>=40)

data_Coronapass<-data_for_ab %>% 
  dplyr::select(c(ID, IgA_or_G_or_M_testC_quantitative, neutralizing_antibodies_quantitative)) %>% filter(IgA_or_G_or_M_testC_quantitative>=1&neutralizing_antibodies_quantitative>=40)

data_VectorBest<-data_for_ab %>% 
  dplyr::select(c(ID, IgG_or_M_testD_quantitative, neutralizing_antibodies_quantitative)) %>% filter(IgG_or_M_testD_quantitative>=1&neutralizing_antibodies_quantitative>=40)

```

```{r}

ggplot(data_Abbott, aes(x = neutralizing_antibodies_quantitative,
                y=IgG_testB_quantitative)) +
   geom_jitter(shape = 21,
               size=4,
               color = "black",
               alpha = 0.8)+
  scale_x_continuous(breaks = c(5, 10, 20, 40, 80, 160, 320, 640), trans = "log2")+
   geom_hline(yintercept = 1,  linetype = "dashed", size = 1, color = "grey50")+
   geom_vline(xintercept = 40,  linetype = "dashed", size = 1, color = "grey50")+
  ggtitle("CMIA Abbott")

cor.test( data_Abbott$neutralizing_antibodies_quantitative, data_Abbott$IgG_testB_quantitative, method = c("spearman"), conf.level = 0.95)


```

```{r}

ggplot(data_Coronapass, aes(x = neutralizing_antibodies_quantitative,
                y=IgA_or_G_or_M_testC_quantitative)) +
   geom_jitter(shape = 21,
               size=4,
               color = "black",
               alpha = 0.8)+
  scale_x_continuous(breaks = c(5, 10, 20, 40, 80, 160, 320, 640), trans = "log2")+
   geom_hline(yintercept = 1,  linetype = "dashed", size = 1, color = "grey50")+
   geom_vline(xintercept = 40,  linetype = "dashed", size = 1, color = "grey50")+
  ggtitle("ELISA Coronapass")

cor.test( data_Coronapass$neutralizing_antibodies_quantitative, data_Coronapass$IgA_or_G_or_M_testC_quantitative, method = c("spearman"), conf.level = 0.95)


```


```{r}

ggplot(data_VectorBest, aes(x = neutralizing_antibodies_quantitative,
                y=IgG_or_M_testD_quantitative)) +
   geom_jitter(shape = 21,
               size=4,
               color = "black",
               alpha = 0.8)+
  scale_x_continuous(breaks = c(5, 10, 20, 40, 80, 160, 320, 640), trans = "log2")+
   geom_hline(yintercept = 1,  linetype = "dashed", size = 1, color = "grey50")+
   geom_vline(xintercept = 40,  linetype = "dashed", size = 1, color = "grey50")+
  ggtitle("ELISA VectorBest")

cor.test( data_VectorBest$neutralizing_antibodies_quantitative, data_VectorBest$IgG_or_M_testD_quantitative, method = c("spearman"), conf.level = 0.95)


```

```{r}

ggplot(data_for_ab, aes(x = neutralizing_antibodies_quantitative,
                y=IgG_testB_quantitative)) +
   geom_jitter(shape = 21,
               size=4,
               color = "black",
               alpha = 0.8)+
  scale_x_continuous(breaks = c(5, 10, 20, 40, 80, 160, 320, 640), trans = "log2")

```

###Дальше открытие века "Кто курит, тот пьет больше кофе"

```{r}
ggplot(data_for_ab, aes(x = smoking, y =coffee_cups_per_day)) +
  geom_boxplot(color="red",
               fill ="pink") +
  stat_compare_means() +
  theme_classic() 


#ggplot(data_for_ab, aes(x = coffee_cups_per_day, y = cigarettes_per_day)) +
  geom_point(color = "darkblue",
         fill = "lightblue",
            shape = 21) +
  theme_classic() 
  
  
 # ggplot(data_for_ab, aes(x = smoking_start_age, y = cigarettes_per_day)) +
  geom_point(size = 3,
             fill = "lightblue",
             shape = 21) +
             geom_smooth(method="lm")+
  theme_classic() 

```


### Гемоглобин


```{r}

ggplot(data_for_ab, aes(x= smoking, y=Hemoglobin_A0)) +
  geom_boxplot() +
   stat_compare_means() +
  geom_jitter()

```

```{r}

fit_smoke<- lm(Hemoglobin_A0 ~ cigarettes_per_day, data_for_ab)

summary_smoke <- summary(fit_smoke)

print(summary_smoke)

ggplot(data_for_ab, aes(x = Hemoglobin_A0 , y = cigarettes_per_day )) +
  geom_point() +
  theme_classic()

```


```{r}

fit_age<- lm(Hemoglobin_A0 ~ age, data_for_ab)

summary_age <- summary(fit_age)

print(summary_smoke)

ggplot(data_for_ab, aes(x = Hemoglobin_A0 , y = age )) +
  geom_point() +
  theme_classic()
```

```{r}

fit_nab<- lm(Hemoglobin_A0 ~  neutralizing_antibodies_quantitative, data_for_ab)

summary_nab <- summary(fit_nab)

print(summary_nab)

ggplot(data_for_ab, aes(x = neutralizing_antibodies_quantitative , y = Hemoglobin_A0)) +
  geom_point() +
  theme_classic()


```


```{r}
tab_model(fit_smoke, fit_age, fit_nab)


```

```{r}
ggplot(data_for_ab, aes(x = Hemoglobin_A0, y = age)) +
  geom_point() +
  theme_classic()

ggplot(data_for_ab, aes(x =Hemoglobin_A0)) +
  geom_histogram(bins = 40, fill = "white", color="darkgrey")+
  theme_classic()

ggplot(data_for_ab, aes(x = Hemoglobin_A0)) +
  geom_density() +
  theme_classic()


ggplot(data_for_ab, aes(x = Hem_norm)) +
  geom_density() +
  theme_classic()


ggplot(data_for_ab, aes(x= male, y=cigarettes_per_day)) +
  geom_boxplot() +
   stat_compare_means() +
  geom_jitter()

data_for_ab %>%
  group_by(male) %>%
  identify_outliers(cigarettes_per_day)


```




               
```{r}



```

```{r}

data_all<-merge(phone_survey_data, other_test_results_matched_to_phone_survey_ids, by = "ID", all.y = T)
str(data_all)


for ( i in c("smoking", "male", "drinks_coffee", "visited_clinic", "travelled") ) {
    data_all[[i]] <- as.factor(data_all[[i]])
}

data_all$smoked_previously <- as.factor(data_all$smoked_previously)

data_smoked<- data_all %>% 
  filter(smoked_previously==1)

data_smoked %>% 
  filter(selftested_covid_positive==1) %>% 
mutate (age_dif=age-smoking_giveup_age) %>% 
  select(age,smoking_giveup_age, age_dif)



```

```{r}
data_cough_now<- table(data_all$district, data_all$cough_now)
prop.table(data_cough_now, 1)



data_cough_past<-table(data_all$district, data_all$cough_past)
prop.table(data_cough_past, 1)



fisher.test(data_all$district, data_all$cough_now, simulate.p.value=TRUE, )

chisq.test(data_all$district, data_all$cough_past)

chisq.test(data_all$district, data_all$smoking_start_age)


```


```{r}
fit_smoke<- lm(Hemoglobin_A0 ~ cigarettes_per_day+income_level, data_all)

summary_smoke <- summary(fit_smoke)

print(summary_smoke)


ggplot(data_all, aes(x = Hemoglobin_A0, y = cigarettes_per_day)) +
  geom_point() +
  geom_smooth() +
  theme_classic()

ggplot(data_all, aes(x =Hemoglobin_A0)) +
  geom_histogram(bins = 40, fill = "white", color="darkgrey")+
  theme_classic()

ggplot(data_all, aes(x = Hemoglobin_A0)) +
  geom_density() +
  theme_classic()

```

