---
title: "FINAL"
author: "Kirill Usoltsev"
date: "11/29/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(ggplot2)

setwd("~/Desktop/BIOINF2021/FINAL_PROJECT/spb_covid_study20-master/FINAL_PROJECT")
load("~/Desktop/BIOINF2021/FINAL_PROJECT/spb_covid_study20-master/FINAL_PROJECT/data/wave2/phone_survey/phone_survey_data.rdata")
load("~/Desktop/BIOINF2021/FINAL_PROJECT/spb_covid_study20-master/FINAL_PROJECT/data/wave2/test_results/other_tests/other_test_results_matched_to_phone_survey_ids.rdata")
```
```{r}

merged_data <- merge(other_test_results_matched_to_phone_survey_ids, phone_survey_data, by = "ID", all.y = T) 

merged_data$age_grouped <- cut(merged_data$age, breaks = c(17, 20, 25, 30, 35, 40, 45, 50,55, 60, 95), labels = c("18-20", "21-25", "26-30", "31-35", "36-40", "41-45", "46-50", "51-55", "56-60", "61+")) 
merged_data$age_grouped_who <- cut(merged_data$age, breaks = c(17, 44, 59, 74, 90, 95), labels = c("18-44", "45-59", "60-74", "75-90", "90+"))
#18-44 (молодые), 45-59 (средний возраст), 60-74 (пожилые) и 75-90 (старческий  возраст) ну и старше (долгожители)

factor_list <- c("male", "travelled", "used_transport", "smoking", "health_level", "lives_alone", "education_level", "age_grouped", "age_grouped_who", "no_pets", "dogs", "cats", "rodents", "birds", "other_pets", "not_sure_pets", "allergies", "chronical_diseases")

data <- merged_data %>% 
  # mutate(log_IgE = log10(IgE_general_quantitative)) %>% 
  mutate(across(factor_list), function(x) x %>% as.factor())

data$age_grouped <- cut(data$age, breaks = c(17, 20, 25, 30, 35, 40, 45, 50,55, 60, 95), labels = c("18-20", "21-25", "26-30", "31-35", "36-40", "41-45", "46-50", "51-55", "56-60", "61+")) 
data$age_grouped_who <- cut(data$age, breaks = c(17, 44, 59, 74, 90, 95), labels = c("18-44", "45-59", "60-74", "75-90", "90+"))
#18-44 (молодые), 45-59 (средний возраст), 60-74 (пожилые) и 75-90 (старческий  возраст) ну и старше (долгожители)

ggplot(data, aes(x = no_pets, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
ggplot(data, aes(x = dogs, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
ggplot(data, aes(x = cats, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
ggplot(data, aes(x = rodents, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
ggplot(data, aes(x = birds, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
ggplot(data, aes(x = other_pets, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
# любопытно, что IgE, кажется, связан с полом (выше у мужчин)
ggplot(data, aes(x = male, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
ggplot(data, aes(x = age_grouped, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
ggplot(data, aes(x = age_grouped_who, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
# education_level
ggplot(data, aes(x = education_level, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
# lives_alone
ggplot(data, aes(x = lives_alone, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
# district
ggplot(data, aes(x = district, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
# health_level
ggplot(data, aes(x = health_level, y = log_IgE)) +
  geom_boxplot(notch = TRUE)

ggplot(data, aes(x = health_level, y = log_IgE)) +
  geom_boxplot(notch = TRUE)

factor_list <- c("male", "travelled", "used_transport", "smoking", "health_level", "lives_alone", "education_level", "age_grouped", "age_grouped_who", "no_pets", "dogs", "cats", "rodents", "birds", "other_pets", "not_sure_pets")

data %>% 
  mutate (across(factor_list), function(x) x %>% as.factor())

for (factor in factor_list) {
  p <- ggplot(data, aes(x = factor, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
  print(p)
}
```


```{r}
summary(data)
ggplot(data, aes(y = log_IgE)) + 
  geom_boxplot()

fit0 <- glm(IgE_general_quantitative ~ no_pets + age_grouped + male, data = data)
summary(fit0)
```

```{r}
# DOGS
ggplot(data, aes(x = chronical_diseases, fill = dogs)) +
    geom_bar(position = "fill")

ggplot(data, aes(x = age_grouped, fill = dogs)) +
    geom_bar(position = "fill")

ggplot(data, aes(x = health_level, fill = dogs)) +
    geom_bar()


```

```{r}

```

$ git --version
