---
title: "NAB"
author: "PAA"
date: "04 11 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(sjPlot)


```



```{r}
load("C:/Users/Sunshine/Desktop/Biostatistics_2021/Final_project/other_test_results_matched_to_phone_survey_ids.rdata")
load("C:/Users/Sunshine/Desktop/Biostatistics_2021/Final_project/phone_survey_data.rdata")
load("C:/Users/Sunshine/Desktop/Biostatistics_2021/Final_project/test_B_results_matched_to_phone_survey_ids.rdata")
load("C:/Users/Sunshine/Desktop/Biostatistics_2021/Final_project/test_C_results_matched_to_phone_survey_ids.rdata")
load("C:/Users/Sunshine/Desktop/Biostatistics_2021/Final_project/test_D_results_matched_to_phone_survey_ids.rdata")

```


```{r}

data_for_ab_IgG1 <-merge(test_B_results_matched_to_phone_survey_ids, test_C_results_matched_to_phone_survey_ids, by = "ID", all.x = T)

data_for_ab_IgG2 <-merge(data_for_ab_IgG1, test_D_results_matched_to_phone_survey_ids, by = "ID", all.x = T)

str(data_for_ab_IgG2)

data_all<-merge(phone_survey_data, other_test_results_matched_to_phone_survey_ids, by = "ID", all.y = T)

str(data_all)

data_for_ab<- merge(data_for_ab_IgG2, data_all, by = "ID", all.x = T)



data_for_ab<- data_for_ab %>% 
  dplyr::select(c(ID, IgG_testB_quantitative, IgA_or_G_or_M_testC_quantitative, IgG_or_M_testD_quantitative, male, district, age, travelled, used_transport, selftested_covid, selftested_covid_positive, street_used_mask, washing_hands_more, health_level, smoking, smoked_previously, smoking_start_age, smoking_giveup_age, cigarettes_per_day, drinks_coffee, coffee_cups_per_day, times_sick, cough_past, fever_past, sorethroat_past, anosmia_past, runnynose_past, fatigue_past, nosymptoms_past, self_medical_checkups, ct_scan, mri, ultrasonography, fluorography, mammography, x_ray, visit_doctor, no_checkups, allergies, chronical_diseases,wears_glasses, lives_alone, num_people_home, under_18, over_65, spouse_or_partner, other_people, no_pets, dogs, cats, rodents, birds, other_pets, not_sure_pets, income_level, work_status, study_status, received_pension_or_other_support, job_search, manages_people, physical_labour, work_with_people, education_level, cough_now, fever_now, sorethroat_now, anosmia_now, runnynose_now, fatigue_now, nosymptoms_now, IgE_general_quantitative, VitaminD, VitaminD_analyzer, IgG_hpylori, Hemoglobin_A0, Cholesterin, Triglycerides, VLDL, LDL, HDL, Atherogenic_index, neutralizing_antibodies_quantitative))


data_for_ab$Hemoglobin_A0

data_for_ab<- data_for_ab %>% 
mutate(Hem_norm = ifelse (Hemoglobin_A0 < 92, "ниже нормы", ifelse (Hemoglobin_A0 >92 & Hemoglobin_A0 <94, "Норма", "Выше нормы")))


data_for_ab%>%
 mutate(numeric=Hem_norm ) %>% 
  count(Hem_norm, numeric)


data_for_ab$male <- as.factor(data_for_ab$male)

data_for_ab$smoking <- as.factor(data_for_ab$smoking)

head(data_for_ab)


 
```

```{r}

data_ab_only<- data_for_ab %>% 
  dplyr::select(c(ID, IgG_testB_quantitative,IgA_or_G_or_M_testC_quantitative, IgG_or_M_testD_quantitative, neutralizing_antibodies_quantitative))

data_Abbott<-data_for_ab %>% 
  dplyr::select(c(ID, IgG_testB_quantitative, neutralizing_antibodies_quantitative)) %>% filter(IgG_testB_quantitative>=1&neutralizing_antibodies_quantitative>=40)

data_Coronapass<-data_for_ab %>% 
  dplyr::select(c(ID, IgA_or_G_or_M_testC_quantitative, neutralizing_antibodies_quantitative)) %>% filter(IgA_or_G_or_M_testC_quantitative>=1&neutralizing_antibodies_quantitative>=40)

data_VectorBest<-data_for_ab %>% 
  dplyr::select(c(ID, IgG_or_M_testD_quantitative, neutralizing_antibodies_quantitative)) %>% filter(IgG_or_M_testD_quantitative>=1&neutralizing_antibodies_quantitative>=40)

```

```{r}

ggplot(data_Abbott, aes(x = neutralizing_antibodies_quantitative,
                y=IgG_testB_quantitative)) +
   geom_jitter(shape = 21,
               size=4,
               color = "black",
               alpha = 0.8)+
  scale_x_continuous(breaks = c(5, 10, 20, 40, 80, 160, 320, 640), trans = "log2")+
   geom_hline(yintercept = 1,  linetype = "dashed", size = 1, color = "grey50")+
   geom_vline(xintercept = 40,  linetype = "dashed", size = 1, color = "grey50")+
  ggtitle("CMIA Abbott")

cor.test( data_Abbott$neutralizing_antibodies_quantitative, data_Abbott$IgG_testB_quantitative, method = c("spearman"), conf.level = 0.95)


```

```{r}

ggplot(data_Coronapass, aes(x = neutralizing_antibodies_quantitative,
                y=IgA_or_G_or_M_testC_quantitative)) +
   geom_jitter(shape = 21,
               size=4,
               color = "black",
               alpha = 0.8)+
  scale_x_continuous(breaks = c(5, 10, 20, 40, 80, 160, 320, 640), trans = "log2")+
   geom_hline(yintercept = 1,  linetype = "dashed", size = 1, color = "grey50")+
   geom_vline(xintercept = 40,  linetype = "dashed", size = 1, color = "grey50")+
  ggtitle("ELISA Coronapass")

cor.test( data_Coronapass$neutralizing_antibodies_quantitative, data_Coronapass$IgA_or_G_or_M_testC_quantitative, method = c("spearman"), conf.level = 0.95)


```


```{r}

ggplot(data_VectorBest, aes(x = neutralizing_antibodies_quantitative,
                y=IgG_or_M_testD_quantitative)) +
   geom_jitter(shape = 21,
               size=4,
               color = "black",
               alpha = 0.8)+
  scale_x_continuous(breaks = c(5, 10, 20, 40, 80, 160, 320, 640), trans = "log2")+
   geom_hline(yintercept = 1,  linetype = "dashed", size = 1, color = "grey50")+
   geom_vline(xintercept = 40,  linetype = "dashed", size = 1, color = "grey50")+
  ggtitle("ELISA VectorBest")

cor.test( data_VectorBest$neutralizing_antibodies_quantitative, data_VectorBest$IgG_or_M_testD_quantitative, method = c("spearman"), conf.level = 0.95)


```

```{r}

ggplot(data_for_ab, aes(x = neutralizing_antibodies_quantitative,
                y=IgG_testB_quantitative)) +
   geom_jitter(shape = 21,
               size=4,
               color = "black",
               alpha = 0.8)+
  scale_x_continuous(breaks = c(5, 10, 20, 40, 80, 160, 320, 640), trans = "log2")

```

